version: '3.8'

networks:
  backend:
    driver: bridge

services:
  golang:
    container_name: golang
    build: ./docker/golang
    tty: true
    environment:
      PGSSLMODE: "disable"
    volumes:
      - ./:/go/src/github.com/ph-piment/onion-scraper
      - ./env:/go/src/env
    networks:
      - backend

  postgres:
    container_name: postgres
    build: ./docker/postgres
    env_file:
      - ./env/.postgres.env
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
      - ./data/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - backend

  pgadmin4: # pgadmin4(http://localhost:16543/) .pgadmin.env account
    container_name: pgadmin4
    image: dpage/pgadmin4
    env_file:
      - ./env/.pgadmin.env
    volumes:
      - ./data/pgadmin/storage:/var/lib/pgadmin/storage
    ports:
      - "16543:80"

    hostname: pgadmin4
    restart: always
    networks:
      - backend
