// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/ph-piment/onion-scraper/app/infrastructure/repository_impl"
	"github.com/ph-piment/onion-scraper/app/usecase/yahoo"
)

// Injectors from wire.go:

func InitializeEvent() usecase.YahooNews {
	yahooNewsRepository := repository_impl.NewYahooNewsRepository()
	yahooNews := usecase.NewYahooNews(yahooNewsRepository)
	return yahooNews
}
