name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    # `container-job` で実行するサービスコンテナ
    services:
      # サービスコンテナへのアクセスに使用されるラベル
      postgres:
        # Docker Hub のイメージ
        image: postgres:13.4-alpine
        # postgres のパスワードを入力する
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: os
        # postgres が起動するまで待機するようにヘルスチェックを設定する
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
      env:
        PGSSLMODE: disable

    - name: Set up Migrate
      run: curl -L https://github.com/k0kubun/sqldef/releases/download/v0.11.4/psqldef_linux_amd64.tar.gz | tar xvz -C /usr/local/bin

    - name: Migrate
      run: cat ./schemas/postgres/* | psqldef -h postgres -U root -W root os

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Coverage
      run: go test -race -coverprofile="coverage.txt" -covermode=atomic ./...

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
